---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./mariadb/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./booklore/ks.yaml
  - ./prowlarr/ks.yaml
  - ./deluge/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./shelfmark/ks.yaml
