---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "enp0s31f6.70",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.70.0/24",
        "rangeStart": "192.168.70.200",
        "rangeEnd": "192.168.70.250",
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "192.168.70.1" }
        ]
      }
    }
