---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: shelfmark-secret
    template:
      data:
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        DELUGE_PASSWORD: "{{ .DELUGE_PASSWORD }}"
  data:
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: "e91cbf49-c0b5-489e-a18e-b3fd007e3015"
    - secretKey: DELUGE_PASSWORD
      remoteRef:
        key: "cb5f2336-4c47-46a6-a7cb-b3fd007d5249"
