---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: booklore-secret
    template:
      data:
        MARIADB_PASSWORD: "{{ .MARIADB_PASSWORD }}"
  data:
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: "bd120844-2e88-4320-990b-b3fd007dfd5d"
