---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: mariadb-secret
    template:
      data:
        MARIADB_ROOT_PASSWORD: "{{ .MARIADB_ROOT_PASSWORD }}"
        MARIADB_PASSWORD: "{{ .MARIADB_PASSWORD }}"
  data:
    - secretKey: MARIADB_ROOT_PASSWORD
      remoteRef:
        key: "00df0c47-3267-4500-b0e0-b3fd007de4d6"
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: "bd120844-2e88-4320-990b-b3fd007dfd5d"
