---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mc-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: mc-server-secret
    template:
      data:
        CF_API_KEY: "{{ .CF_API_KEY }}"
  data:
  - secretKey: CF_API_KEY
    remoteRef:
      key: "39dd1abf-376c-4c24-b5cd-b3930004f990"