---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deluge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: deluge-secret
    template:
      data:
        VPN_SERVICE_PROVIDER: airvpn
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_PRESHARED_KEY: "{{ .WIREGUARD_PRESHARED_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        SERVER_COUNTRIES: "{{ .SERVER_COUNTRIES }}"
        DELUGE_PASSWORD: "{{ .DELUGE_PASSWORD }}"
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: "fc5241cd-35c7-4b3f-9af2-b3fd007c8bcc"
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: "73a78fc9-9ff5-4186-adb3-b3fd007cb78e"
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: "bf9d5113-16bb-4408-9950-b3fd007cda46"
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: "ba4cb37a-3fe4-428b-88c6-b3fd007d0adf"
    - secretKey: DELUGE_PASSWORD
      remoteRef:
        key: "cb5f2336-4c47-46a6-a7cb-b3fd007d5249"
