---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_2/./-}-production"
spec:
  dnsNames:
    - "${SECRET_DOMAIN_2}"
    - "*.${SECRET_DOMAIN_2}"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: "${SECRET_DOMAIN_2/./-}-production-tls"
  usages:
    - digital signature
