apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/ZM1kyuK/DgiZL+53isY+A==,iv:CLG3gb10kBypPxG0AofQxuK6ibxJUAzSGelvQplCS7E=,tag:nU5JD9iVjnhEkGMhU5CF5g==,type:str]
  SECRET_DOMAIN_2: ENC[AES256_GCM,data:QeJEt2objGwEXcM=,iv:fgK4ZlxFiyhAFuZ+JiuEg1lgRSOubFF1SUGRGOPqY34=,tag:HWgjMFWPm1zt6H9I+vHmDg==,type:str]
sops:
  age:
    - recipient: age1dmr7gvh2d2j7mlm5ldz6nxgua5qnvtzz77s0hnwznryjgx5pzeasp5q2a9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd1I4eWFmTUZNd0hKOSs5
        Yk4vR09MVjF4YytNU2lJaDRqbmxScnIyb2owCnpQNnJpNHUwZVd0OTNYeCtqZkR3
        eXpUREdJSDFseVMwSEpWN2FlNTNkOUkKLS0tIDlER1o5RmVpc3J4RHZMMmtmS3U0
        ZmJNbXlKODduUVduV0pEVCtnQlpoLzAKNpjBlRhudvq9R2BCMs5t8tZrVl9tbUZW
        vxMxzTmXL5+/XaemTp49iEB/gI3kLktsCT7QDu68LyxHEhIbj6fvhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T05:43:08Z"
  mac: ENC[AES256_GCM,data:mZ/cIj9nwW0BaqeLmn8x6QQzwM+Oy6n/1JRbMvWTXEzd+lYAcqj0MKMyByGzr3eC5SXj9uQIHQQL7v2GFN+SpNRuPrP9Htg2mcYhT9k9ciWDePwgQooJf4CzcxkjenOsLrhhwJR01sMGbLIEPmxhbzgdVR9Ci61jrb236nfaSC4=,iv:ZOqR7IE6mTRxOEvTvmRHTN5BgkJT7a9IWwVALTxH7RU=,tag:ExTJ1dfdjjhcKqs3UUeSUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
